### ISSUE TITLE
点击空白处工具栏自动缩回

### ISSUE THREAD

**Issue by MiniWong** [ionepub/shimo-sidebar#1]
实际使用发现如果点击空白处工具自动缩回就好了！
不知道其他人有没有这个想法

**Comment by ionepub** [comment]
感谢使用。

本身是针对大屏和小屏做了一点高度的优化的，尽量让工具不妨碍文档书写，如果需求较多，会考虑的。

**Comment by ionepub** [comment]
@MiniWong  1.1版新增了点击空白处自动缩回的功能
