### ISSUE TITLE
将recent并入sidebar

### ISSUE THREAD

**Issue by calliu** [ionepub/shimo-sidebar#2]
非常感谢您的插件，有了您的这两个插件，大大的提高了我的工作效率！在使用的过程中，个人感觉有两个点可以完善一下，希望您能评估下：

1. 优化sidebar的树形结构，将三列合并为一列的树形结构，目录到文件逐级展开；一来节省左侧空间，二来也符合mac和win操作系统培育的用户使用习惯；

2. 将recent并入sidebar中，改为默认展开，将recent和sidebar分上下区域呈现；从操作目的上来说，不管是使用recent还是sidebar，最终的目的都是更加快捷的切换文档，所以在功能属性上属于同一个区块，同时考虑到目前PC屏的尺寸比以及浏览器顶部的空间占有，纵向空间就显得要比横向空间珍贵。

**Comment by ionepub** [comment]
感谢使用。

首先，目录展示方式是参考的mac Finder，逐层预览的方式，也是借用之前的一个repo：https://github.com/ionepub/FilePro；

也有考虑过用树形目录，但是有几点考虑：

1. 层级关系靠缩进，有时候列表长，可能父子层级关系没那么明朗
2. 树形目录相对来说刷新比较不方便，如果协作者在目录中添加或者删除了文档，可能需要通过F5刷新整个页面来获取新的目录结构内容，对用户来说，操作成本比较大

目前石墨并没有分享整个文件夹的功能，后期可能会配合API另外开发一款插件，做类似微信公众平台开发文档类似的效果，届时应该会采用树形目录（也是想借助石墨做接口文档管理）。

![image](https://cloud.githubusercontent.com/assets/16647246/23007796/e8f7a8f4-f445-11e6-8f1c-08e499ade125.png)


关于两个插件的合并，后面应该会做的，不过布局可能不会有太大变化。

最后，感谢宝贵意见。有问题可以再提。
